pipeline {

    agent {
        label 'docker-maven-trivy'
    }

    tools {
        maven 'maven3'
    }

    environment {
        SONAR_IP = '172.31.34.176'
        ECR_REGISTRY = '560461521995.dkr.ecr.us-east-1.amazonaws.com'
        IMAGE_REPO = "${ECR_REGISTRY}/cwvj-devsecops-demo"
        TRIVY_DISABLE_VEX_NOTICE = 'true'
    }

    stages {

        stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs --exit-code 1 --severity HIGH,CRITICAL .'
            }
        }

        stage('Build & Sonar') {
            steps {

                dir('Project-01/java-maven') {

                    withCredentials([
                        string(
                            credentialsId: 'sonarqube-token',
                            variable: 'SONAR_TOKEN'
                        )
                    ]) {

                        sh '''
                            mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                              -Dsonar.projectKey=devsecops-demo \
                              -Dsonar.host.url="http://${SONAR_IP}:9000" \
                              -Dsonar.token="${SONAR_TOKEN}" \
                              -Dsonar.qualitygate.wait=true
                        '''
                    }
                }
            }
        }
        stage('ECR Login') {
            steps {
              sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY'
            }
        }
        stage('Build Image') {
            steps {
                dir('Project-01/java-maven') {
                     sh 'export DOCKER_BUILDKIT=0 && docker build --platform linux/amd64 -t "$IMAGE_REPO:$BUILD_NUMBER" -t "$IMAGE_REPO:latest" .'
               }
             }
        }
        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL "$IMAGE_REPO:$BUILD_NUMBER"'
            }
        }
        stage('Push to ECR') {
             steps {
                dir('Project-01/java-maven') {

                    sh 'docker push "$IMAGE_REPO:$BUILD_NUMBER"'
                    sh 'docker push "$IMAGE_REPO:latest"'
                }
            }
        }
        stage('Update Deployment') {
            steps {
                sh 'sed -i "s|image:.*|image: $IMAGE_REPO:$BUILD_NUMBER|g" deploy-svc.yaml'
            }
        }
    }
}

